/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Beetle.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/Beetle.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.mesh_0.geometry} material={materials.Mat_1} />
      <mesh geometry={nodes.mesh_1.geometry} material={materials.Mat_2} />
      <mesh geometry={nodes.mesh_2.geometry} material={materials.Mat_3} />
    </group>
  )
}

useGLTF.preload('/Beetle.gltf')
